**TASK 01: Load all three datasets**

In [ ]:
import pandas as pd
import numpy as np

students_df = pd.read_csv("/content/students.csv")
attendance_df = pd.read_csv('/content/attendance.csv')
results_df = pd.read_csv('/content/results.csv')

In [ ]:
students_df.head()

   StudentID   Name  Gender Department   Age
0        101    Ali    Male         CS  20.0
1        102   Sara  Female         SE  21.0
2        103  Ahmed    male         CS  22.0
3        104   Hina  FEMALE         AI  20.0
4        105  Usman       M         se   NaN

In [ ]:
attendance_df.head()

   StudentID  ClassesHeld  ClassesAttended
0        101           40               37
1        102           40               32
2        103           40               22
3        104           40               39
4        105           40               31

In [ ]:
results_df.head()

   StudentID  Quiz1  Quiz2  Assignment  Midterm  Final
0        101    8.0    9.0          18       25     35
1        102    7.0    8.0          16       22     31
2        103    5.0    6.0          13       16     22
3        104    9.0    9.0          20       28     38
4        105    NaN    7.0          15       20     28

**Task 02: Understand the structure**

In [ ]:
students_df.shape

(12, 5)

In [ ]:
students_df.columns

Index(['StudentID', 'Name', 'Gender', 'Department', 'Age'], dtype='object')

In [ ]:
students_df.dtypes

StudentID       int64
Name           object
Gender         object
Department     object
Age           float64
dtype: object

In [ ]:
students_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   12 non-null     int64
 1   Name        12 non-null     object
 2   Gender      12 non-null     object
 3   Department  12 non-null     object
 4   Age         11 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 612.0+ bytes

In [ ]:
numeric = students_df.select_dtypes(include=np.number).columns
categorical = students_df.select_dtypes(exclude = np.number).columns

In [ ]:
print("Numeric Datatypes:", list(numeric))
print("Catagorical Datatypes:", list(categorical))

Numeric Datatypes: ['StudentID', 'Age']
Catagorical Datatypes: ['Name', 'Gender', 'Department']

In [ ]:
attendance_df.shape

(11, 3)

In [ ]:
attendance_df.columns

Index(['StudentID', 'ClassesHeld', 'ClassesAttended'], dtype='object')

In [ ]:
attendance_df.dtypes

StudentID          int64
ClassesHeld        int64
ClassesAttended    int64
dtype: object

In [ ]:
attendance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   StudentID        11 non-null     int64
 1   ClassesHeld      11 non-null     int64
 2   ClassesAttended  11 non-null     int64
dtypes: int64(3)
memory usage: 396.0 bytes

In [ ]:
numeric = attendance_df.select_dtypes(include = np.number).columns
categorical = attendance_df.select_dtypes(exclude = np.number).columns

In [ ]:
print("Numeric Datatypes:", list(numeric))
print("Catagorical Datatypes:", list(categorical))

Numeric Datatypes: ['StudentID', 'ClassesHeld', 'ClassesAttended']
Catagorical Datatypes: []

In [ ]:
results_df.shape

(11, 6)

In [ ]:
results_df.columns

Index(['StudentID', 'Quiz1', 'Quiz2', 'Assignment', 'Midterm', 'Final'], dtype='object')

In [ ]:
results_df.dtypes

StudentID       int64
Quiz1         float64
Quiz2         float64
Assignment      int64
Midterm         int64
Final           int64
dtype: object

In [ ]:
results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   11 non-null     int64
 1   Quiz1       10 non-null     float64
 2   Quiz2       10 non-null     float64
 3   Assignment  11 non-null     int64
 4   Midterm     11 non-null     int64
 5   Final       11 non-null     int64
dtypes: float64(2), int64(4)
memory usage: 660.0 bytes

In [ ]:
numeric = results_df.select_dtypes(include = np.number).columns
categorical = results_df.select_dtypes(exclude = np.number).columns

In [ ]:
print("Numeric Datatypes:", list(numeric))
print("Catagorical Datatypes:", list(categorical))

Numeric Datatypes: ['StudentID', 'ClassesHeld', 'ClassesAttended']
Catagorical Datatypes: []

**TASK 03: Investigate missing values**

In [ ]:
students_df.isnull().sum()

StudentID     0
Name          0
Gender        0
Department    0
Age           1
dtype: int64

In [ ]:
students_df.columns[students_df.isnull().any()]

Index(['Age'], dtype='object')

In [ ]:
attendance_df.isnull().sum()

StudentID          0
ClassesHeld        0
ClassesAttended    0
dtype: int64

In [ ]:
attendance_df.columns[attendance_df.isnull().any()]

Index([], dtype='object')

In [ ]:
results_df.isnull().sum()

StudentID     0
Quiz1         1
Quiz2         1
Assignment    0
Midterm       0
Final         0
dtype: int64

In [ ]:
results_df.columns[results_df.isnull().any()]

Index(['Quiz1', 'Quiz2'], dtype='object')

**Task 04: Investigate duplicates**

In [ ]:
students_df.duplicated().sum()

np.int64(1)

In [ ]:
students_df[students_df.duplicated(keep=False)]

    StudentID  Name Gender Department   Age
9         110  Zara      F         AI  21.0
10        110  Zara      F         AI  21.0

In [ ]:
attendance_df.duplicated().sum()

np.int64(0)

In [ ]:
results_df.duplicated().sum()

np.int64(0)

**TASK 5: Find Impossible attendance**

In [ ]:
attendance_df[attendance_df['ClassesAttended'] > attendance_df['ClassesHeld']]

   StudentID  ClassesHeld  ClassesAttended
9        110           40               41

**CLEAN THE DATA**

**Task 06: Remove duplicate StudentIDs**

In [ ]:
clean_students = students_df.drop_duplicates(subset='StudentID')
clean_students

    StudentID    Name  Gender Department   Age
0         101     Ali    Male         CS  20.0
1         102    Sara  Female         SE  21.0
2         103   Ahmed    male         CS  22.0
3         104    Hina  FEMALE         AI  20.0
4         105   Usman       M         se   NaN
5         106  Fatima  Female         CS  23.0
6         107   Bilal    Male         AI  21.0
7         108  Ayesha  female         CS  22.0
8         109   Hamza    Male         SE  20.0
9         110    Zara       F         AI  21.0
11        111  Danish    Male         CS  35.0

In [ ]:
clean_students.duplicated().sum()

np.int64(0)

**Task 07: Standardize Gender**

In [ ]:
clean_students['Gender'].astype(str).str.strip().str.title()
clean_students['Gender'].replace({'M': 'Male', 'F': 'Female'}, inplace=True)

/tmp/ipykernel_765/2127915422.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_students['Gender'].replace({'M': 'Male', 'F': 'Female'}, inplace=True)
/tmp/ipykernel_765/2127915422.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_students['Gender'].replace({'M': 'Male', 'F': 'Female'}, inplace=True)

In [ ]:
clean_students

    StudentID    Name  Gender Department   Age
0         101     Ali    Male         CS  20.0
1         102    Sara  Female         SE  21.0
2         103   Ahmed    male         CS  22.0
3         104    Hina  FEMALE         AI  20.0
4         105   Usman       M         se   NaN
5         106  Fatima  Female         CS  23.0
6         107   Bilal    Male         AI  21.0
7         108  Ayesha  female         CS  22.0
8         109   Hamza    Male         SE  20.0
9         110    Zara       F         AI  21.0
11        111  Danish    Male         CS  35.0

**Task 08: Standardize Department**

In [ ]:
clean_students["Department"]=clean_students['Department'].str.upper()

/tmp/ipykernel_765/3637722957.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_students["Department"]=clean_students['Department'].str.upper()

In [ ]:
clean_students

    StudentID    Name  Gender Department   Age
0         101     Ali    Male         CS  20.0
1         102    Sara  Female         SE  21.0
2         103   Ahmed    male         CS  22.0
3         104    Hina  FEMALE         AI  20.0
4         105   Usman       M         SE   NaN
5         106  Fatima  Female         CS  23.0
6         107   Bilal    Male         AI  21.0
7         108  Ayesha  female         CS  22.0
8         109   Hamza    Male         SE  20.0
9         110    Zara       F         AI  21.0
11        111  Danish    Male         CS  35.0

**Task 09: Handle Missing Age**

In [ ]:
clean_students['Age'] = clean_students['Age'].fillna(clean_students['Age'].median())

/tmp/ipykernel_765/3523153401.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_students['Age'] = clean_students['Age'].fillna(clean_students['Age'].median())

In [ ]:
clean_students

    StudentID    Name  Gender Department   Age
0         101     Ali    Male         CS  20.0
1         102    Sara  Female         SE  21.0
2         103   Ahmed    male         CS  22.0
3         104    Hina  FEMALE         AI  20.0
4         105   Usman       M         SE  21.0
5         106  Fatima  Female         CS  23.0
6         107   Bilal    Male         AI  21.0
7         108  Ayesha  female         CS  22.0
8         109   Hamza    Male         SE  20.0
9         110    Zara       F         AI  21.0
11        111  Danish    Male         CS  35.0

**Task 10: Clean missing quiz marks**

In [ ]:
clean_results = results_df.copy()

In [ ]:
clean_results['Quiz1'].fillna(clean_results['Quiz1'].mean(), inplace=True)
clean_results['Quiz2'].fillna(clean_results['Quiz2'].mean(), inplace=True)

/tmp/ipykernel_765/3620307659.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_results['Quiz1'].fillna(clean_results['Quiz1'].mean(), inplace=True)
/tmp/ipykernel_765/3620307659.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_results['Quiz2'].fillna(clean_results['Quiz2'].mean(), inplace=True)

In [ ]:
clean_results

    StudentID  Quiz1  Quiz2  Assignment  Midterm  Final
0         101    8.0    9.0          18       25     35
1         102    7.0    8.0          16       22     31
2         103    5.0    6.0          13       16     22
3         104    9.0    9.0          20       28     38
4         105    6.8    7.0          15       20     28
5         106    8.0    8.0          17       24     34
6         107    4.0    5.0          10       14     20
7         108    9.0   10.0          19       27     37
8         109    6.0    7.0          14       19     27
9         110    7.0    8.0          18       23     33
10        111    5.0    7.7          12       15     18

**Task 11: Correct invalid attendance**

In [ ]:
clean_attendance = attendance_df.copy()

In [ ]:
# Decision: If ClassesAttended > ClassesHeld, cap Attended at the maximum possible ClassesHeld.
# This assumes perfect attendance with a data-entry typo rather than wiping out the row.
invalid_attendance = clean_attendance['ClassesAttended'] > clean_attendance['ClassesHeld']
clean_attendance.loc[invalid_attendance, 'ClassesAttended'] = clean_attendance.loc[invalid_attendance, 'ClassesHeld']

In [ ]:
clean_attendance

    StudentID  ClassesHeld  ClassesAttended
0         101           40               37
1         102           40               32
2         103           40               22
3         104           40               39
4         105           40               31
5         106           40               35
6         107           40               18
7         108           40               36
8         109           40               28
9         110           40               40
10        111           40               25

**CREATE USEFUL FEATURE**

**Task 12: Attendance percentage**

In [ ]:
clean_attendance['AttendancePercentage'] = (clean_attendance['ClassesAttended'] / clean_attendance['ClassesHeld']) * 100

clean_attendance['AttendancePercentage'] = clean_attendance['AttendancePercentage'].round(2)

print(clean_attendance.head())

   StudentID  ClassesHeld  ClassesAttended  AttendancePercentage
0        101           40               37                  92.5
1        102           40               32                  80.0
2        103           40               22                  55.0
3        104           40               39                  97.5
4        105           40               31                  77.5

**Task 13: Assessment totals**

In [ ]:
clean_results

    StudentID  Quiz1  Quiz2  Assignment  Midterm  Final
0         101    8.0    9.0          18       25     35
1         102    7.0    8.0          16       22     31
2         103    5.0    6.0          13       16     22
3         104    9.0    9.0          20       28     38
4         105    6.8    7.0          15       20     28
5         106    8.0    8.0          17       24     34
6         107    4.0    5.0          10       14     20
7         108    9.0   10.0          19       27     37
8         109    6.0    7.0          14       19     27
9         110    7.0    8.0          18       23     33
10        111    5.0    7.7          12       15     18

In [ ]:
clean_results['QuizTotal'] = clean_results['Quiz1'] + clean_results['Quiz2']
clean_results['TotalMarks'] = clean_results['QuizTotal'] + clean_results['Assignment'] + clean_results['Midterm'] + clean_results['Final']
clean_results['Percentage'] = (clean_results['TotalMarks'] / 100) * 100
clean_results.head()

,StudentID,Quiz1,Quiz2,Assignment,Midterm,Final,QuizTotal,TotalMarks,Percentage
0,101,8.0,9.0,18,25,35,17.0,95.0,95.0
1,102,7.0,8.0,16,22,31,15.0,84.0,84.0
2,103,5.0,6.0,13,16,22,11.0,62.0,62.0
3,104,9.0,9.0,20,28,38,18.0,104.0,104.0
4,105,6.8,7.0,15,20,28,13.8,76.8,76.8

**Task 14 - Performance category**

In [ ]:
def categorize_performance(percentage):
    if percentage >= 85:
        return 'Excellent'
    elif 70 <= percentage < 85:
        return 'Good'
    elif 60 <= percentage < 70:
        return 'Average'
    else:
        return 'Needs Improvement'

clean_results['Performance'] = clean_results['Percentage'].apply(categorize_performance)
clean_results.head()

,StudentID,Quiz1,Quiz2,Assignment,Midterm,Final,QuizTotal,TotalMarks,Percentage,Performance
0,101,8.0,9.0,18,25,35,17.0,95.0,95.0,Excellent
1,102,7.0,8.0,16,22,31,15.0,84.0,84.0,Good
2,103,5.0,6.0,13,16,22,11.0,62.0,62.0,Average
3,104,9.0,9.0,20,28,38,18.0,104.0,104.0,Excellent
4,105,6.8,7.0,15,20,28,13.8,76.8,76.8,Good

**Task 15 - Export your cleaned files**

In [ ]:
clean_students.to_csv('students_clean.csv', index=False)
clean_attendance.to_csv('attendance_clean.csv', index=False)
clean_results.to_csv('results_clean.csv', index=False)

print("Cleaned datasets exported successfully!")

Cleaned datasets exported successfully!

**Independent Challenge**

In [ ]:
def get_data_quality_metrics(df, df_name):
    rows = df.shape[0]
    columns = df.shape[1]
    missing_values = df.isnull().sum().sum()
    duplicate_ids = df.duplicated(subset=['StudentID']).sum() if 'StudentID' in df.columns else 0
    return {
        'Dataset': df_name,
        'Rows': rows,
        'Columns': columns,
        'MissingValues': missing_values,
        'DuplicateIDs': duplicate_ids
    }
# Get metrics for each cleaned dataset
students_quality = get_data_quality_metrics(clean_students, 'clean_students')
attendance_quality = get_data_quality_metrics(clean_attendance, 'clean_attendance')
results_quality = get_data_quality_metrics(clean_results, 'clean_results')
# Create a DataFrame from the metrics
data_quality_report = pd.DataFrame([
    students_quality,
    attendance_quality,
    results_quality
])
data_quality_report.to_csv('data_quality_report.csv', index=False)
print("Data quality report generated and exported as 'data_quality_report.csv':")
print(data_quality_report)

Data quality report generated and exported as 'data_quality_report.csv':
            Dataset  Rows  Columns  MissingValues  DuplicateIDs
0    clean_students    11        5              0             0
1  clean_attendance    11        4              0             0
2     clean_results    11       10              0             0